image:
  repository: ghcr.io/gizemcell/insider-one-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

config:
  addr: ":8080"

resources: {}

ingress:
  enabled: false

autoscaling:
  enabled: false

networkPolicy:
  enabled: false

podDisruptionBudget:
  enabled: false