replicaCount: 1

image:
  tag: sha-e534506
  pullPolicy: Always

ingress:
  enabled: true
  host: dev.api.insider.local

resources:
  requests:
    cpu: 50m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 64Mi