replicaCount: 3

image:
  tag: v0.1.0
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: nginx
  host: api.insider-service.com
  tls:
    - secretName: insider-service-tls
      hosts:
        - api.insider-service.com

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

networkPolicy:
  enabled: true
  ingressControllerNamespace: ingress-nginx

podDisruptionBudget:
  enabled: true
  minAvailable: 2

resources:
  requests:
    cpu: 200m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi