apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "insider-service.name" . }}
  labels:
    {{- include "insider-service.labels" . | nindent 4 }}
data:
  ADDR: {{ .Values.config.addr | quote }}
