apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "insider-service.name" . }}
  labels:
    {{- include "insider-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "insider-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "insider-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: insider-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "insider-service.name" . }}
            {{- if .Values.secret }}
            - secretRef:
                name: {{ include "insider-service.name" . }}
            {{- end }}
          startupProbe:
            httpGet:
              path: /healthz
              port: http
            failureThreshold: 12
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 10
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
