apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "insider-service.name" . }}
  labels:
    release: monitoring
spec:
  groups:
    - name: insider-service.rules
      rules:
        - alert: HighErrorRate
          expr: |
            (
              sum(rate(http_requests_total{status=~"5.."}[5m]))
              /
              sum(rate(http_requests_total[5m]))
            ) > 0.05
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "High HTTP error rate"
            description: "Error rate is above 5%"