{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pingsvc.name" . }}
  labels:
    {{- include "pingsvc.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secret | nindent 2 }}
{{- end }}
