{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "insider-service.name" . }}
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - prod
      - dev

  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "insider-service.name" . }}

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}